/*Copyright (c) 2011-2013 Moat Inc. All Rights Reserved.*/
try{(function(q,r){function $(a,k){for(var h=[a],c=1;c<=k;c++)h.push(a+c),h.push(a-c);return h[r.floor(r.random()*h.length)]}function aa(){var a=$(8,2);this.inSample=function(){return 0==r.floor(r.random()*a)};this.getMultiplier=function(){return a}}function ba(a){var k=new aa;if(F&&k.inSample()){var h=x.document;(a=h.getElementsByTagName("script")[0])||(a=h.getElementsByTagName("head")[0]);if(a){var h=h.createElement("script"),c="//"+m.b.j+"/moatpg195nulK89/moatad.js",b={i:"NYTIMES2"};(k=k.getMultiplier())&&
(b.cm=k);c+="#"+m.i.e(b);h.src=c;h.async=!0;h.type="text/javascript";a.parentNode.insertBefore(h,a);a=!0}else a=!1;return a}return!1}function W(){for(var a in t)t.hasOwnProperty(a)&&m.e.i(t[a]);for(a=0;a<M.length;a++)window.clearTimeout(M[a]);for(a=0;a<N.length;a++)window.clearInterval(N[a]);m.f.k()}var m={};(function(a){function k(a){return a&&a.document&&a.location&&a[b+d]&&a[e+g]}function h(a){if(null==a||k(a))return!1;var b=a.length;return 1===a.nodeType&&b?!0:"string"===typeof a||c(a)||0===b||
"number"===typeof b&&0<b&&b-1 in a}function c(b){return"[object Array]"===a.a.w.toString.call(b)}a.a={};a.a.a=3E3;a.a.b=function(){var a=/Firefox\/(\d+)/.exec(navigator.userAgent);return a?14<parseInt(a[1],10):!1}();a.a.c=function(){var b;b=/^(?:[a-z]+:\/\/|:?\/?\/)?(?:www\.)?([^\/:]*)/i;b=!a.b.a&&a.b.b?(b=a.b.b.match(b))&&b[1]?b[1]:a.b.c.location.hostname:a.b.c.location.hostname;var c=b.match(/.*\.([^\.]*\..*)/i);return c&&c[1]?decodeURIComponent(c[1]):decodeURIComponent(b)};a.a.d=function(){var b=
a.a.e();return 5===b||6===b||7===b};a.a.e=function(){if(!navigator)return null;var a=navigator.userAgent;return"Microsoft Internet Explorer"==navigator.appName?parseInt(a.replace(/^.*MSIE (\d+).*$/,"$1"),10):"Netscape"==navigator.appName&&(a=a.match(/Trident\/.*rv:(\d+)/))?parseInt(a[1],10):null};a.a.f=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return!0;return!1};a.a.g=function(a,b){for(var c=0;c<a.length;c++)if(-1<b.indexOf(a[c]))return a[c];return!1};a.a.h=function(a){return new q-a.de};
a.a.i=function(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]};a.a.j=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|BB10|Windows Phone/.exec(navigator.userAgent)};a.a.k=function(){return null!==/iPhone|iPod/.exec(navigator.userAgent)};a.a.l=function(){var a=navigator.userAgent;return a.match(/iPhone|iPod|iPad/)&&!a.match(/Safari/i)};a.a.m=function(){var a=window;try{return"undefined"!==typeof a.external&&"undefined"!==
typeof a.external.InPrivateFilteringEnabled&&a.external.InPrivateFilteringEnabled()||"undefined"!==typeof a.external&&"undefined"!==typeof a.external.msTrackingProtectionEnabled&&a.external.msTrackingProtectionEnabled()||"undefined"!==typeof a._gaUserPrefs&&a._gaUserPrefs.ioo&&a._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==typeof a._gaUserPrefs&&!0===a._gaUserPrefs}catch(b){return!1}};a.a.getAttribute=function(a,
b){return a[b]||a.getAttribute(b)};a.a.n=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&(b+=1);return b};a.a.o=function(b,c){return a.a.p(b)&&!0!==b[y]?!0:!1};a.a.p=function(b){return b.offsetWidth*b.offsetHeight>=a.a.a};a.a.q=function(a,b){var c=!1,d=b.body,e=d&&d.firstChild;d&&e&&(d.insertBefore(a,e),c=!0);return c};a.a.r=function(){var a;return function(){if(!a)a:{for(var b=document.getElementsByTagName("script"),c=b.length-1;-1<c;c--)if((a=b[c])&&a.src&&a.src.indexOf&&-1!==a.src.indexOf(ca+
"/moatad.js")&&("undefined"===typeof a[y]||!0!==a[y])){a[y]=!0;break a}a=void 0}return a?(a[y]=!0,a):null}}();a.a.s=function(a){try{return-1!==(a.src||a.getAttribute("src")).indexOf("psd=1")}catch(b){return!1}};a.a.t=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};a.a.previousElementSibling=function(a){if(a.previousElementSibling)return a.previousElementSibling;for(;a=a.previousSibling;)if(1===a.nodeType)return a};a.a.u=function(a,b,c){"undefined"!==typeof c&&(a[b]=c)};a.a.filter=
function(a,b){for(var c=[],d=0;d<a.length;d++)b(a[d])&&c.push(a[d]);return c};a.a.v=function(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a(b[d]));return c};var b="ale",d="rt",e="setInte",g="rval";a.a.w={};a.a.x=c;a.a.y=k;a.a.z=h;a.a.forEach=function(a,b,c){var d;if(a)if("function"===typeof a)for(d in a){if("prototype"!=d&&"length"!=d&&"name"!=d&&(!a.hasOwnProperty||a.hasOwnProperty(d))){var e=b.call(c,a[d],d);if("boolean"===typeof e&&!e)break}}else if("function"===typeof a.every)a.every(function(a,
d,s){a=b.call(c,a,d);return!("boolean"===typeof a&&!a)});else if(h(a))for(d=0;d<a.length&&(e=b.call(c,a[d],d),"boolean"!==typeof e||e);d++);else for(d in a)if(a.hasOwnProperty(d)&&(e=b.call(c,a[d],d),"boolean"===typeof e&&!e))break;return a}})(m);(function(a){function k(a){try{var b=typeof a.location.toString;if("undefined"===b||"unknown"===b)return!0;var d=typeof a.document;return"undefined"===d||"unknown"===d?!0:!1}catch(e){return!0}}a.b={};a.b.d="MoatSuperV4";a.b.e=0;a.b.f=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");
a.b.g=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");a.b.h=-1!==navigator.userAgent.indexOf("MSIE");a.b.i=(new q).getTime();a.b.protocol=function(){var a;try{a=window.location.protocol}catch(b){a=document.createElement("a"),a.href="",a=a.protocol}return a}();a.b.j=("https:"===a.b.protocol?"z":"js")+".moatads.com";a.b.k=window!=window.parent;var h=k(window.parent);a.b.l=a.b.k&&!h;a.b.a=h?!1:!k(window.top);a.b.c=a.b.a?window.top:a.b.l?window.parent:window;a.b.b=a.b.c.document.referrer})(m);
(function(a){function k(a){return function(){var b=!1;return function(d){try{a(d)}catch(e){if(!b){b=!0;d=e.name+" in callback: "+e.message+", stack="+e.stack;try{var g="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("NYTIMES2")+"&ac=1&k="+escape(d)+"&ar="+escape("099702a-clean")+"&j="+escape(document.referrer)+"&cs="+(new q).getTime();(new Image(1,1)).src=g}catch(f){}}}}}()}a.c={};var h={};a.c.a=h;a.c.b=function(a,b,d,e){d=k(d);a.addEventListener?a.addEventListener(b,d,
!1):a.attachEvent("on"+b,d);!1!==e&&(h[b+e]=d)};a.c.c=function(a,b,d,e){var g=b+e;d=!1!==e?h[g]:d;try{a&&a.removeEventListener?a.removeEventListener(b,d,!1):a&&a.detachEvent&&a.detachEvent("on"+b,d)}catch(f){}delete h[g]};a.c.d=function(a,b){a=k(a);var d=setInterval(a,b);N.push(d);return d};a.c.e=function(a,b){a=k(a);var d=setTimeout(a,b);M.push(d);return d};a.c.f=function(c,b,d,e){var g=0,f=function(){g+=1;!0!==c()&&(g<b?a.c.e(f,d):"function"===typeof e&&e())};f()};a.c.g=k})(m);(function(a){function k(){this.height=
this.width=this.absTop=this.absLeft=0;this.update=function(a){this.absLeft=a.left+e("left",a.win);this.absTop=a.top+e("top",a.win);this.width=a.width;this.height=a.height}}function h(b,d){var c=b.zr;f.hasOwnProperty(c)||(f[c]=new k);var e=d||new a.d.h(b.aa);f[c].update(e)}function c(a,b){for(var d=[],c=0;c<b.length;c++)d.push(a(b[c]));return d}function b(b){var d,e=a.e.b(b.el,b.win),e=c(function(b){return new a.d.h(b)},e);e.unshift(b);var f=e.length;b=new a.d.h(b.el,a.b.c);for(var g=0;g<f;g++){var h=
e[g];0===g?d=h:(d.changeReferenceFrame(h),b.changeReferenceFrame(h));h=h.getViewportRect(g<f-1?e[g+1]:!1);d=a.d.j(d,h)}return{visibleRect:d,cumulRect:b,parentArea:e[e.length-1].calcArea()}}function d(a,b,d,c){a=r.max(a,d);b=r.min(b,c);return b>a?[a,b]:[0,0]}function e(a,b){b||(b=window);var d=b.document.documentElement,c=b.document.body;return"left"===a?b.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft:b.pageYOffset||d&&d.scrollTop||c&&c.scrollTop}a.d={};var g=a.b.a,f={};a.d.a=0.5;a.d.b=0.3;a.d.c=236425;
a.d.d=function(d,c){var e;e=new a.d.h(d.aa,c);h(d,e);var f=e.height,g=e.width,k=e.calcArea();if(0===k)e={area:k,percv:0};else{var s=b(e),K=s.visibleRect.calcArea(),H=K/k,m;b:{var w=s.cumulRect,z=s.cumulRect.getViewportRect();if(0>w.top&&0<w.bottom)m=-w.top;else if(0<=w.top&&w.top<=z.height)m=0;else{m={yMin:-1,yMax:-1};break b}if(0<=w.bottom&&w.bottom<=z.height)w=w.height;else if(w.bottom>z.height&&w.top<z.height)w=w.height-(w.bottom-z.height);else{m={yMin:-1,yMax:-1};break b}m={yMin:m,yMax:w}}e={area:k,
visibleArea:K,percv:H,yMinMax:m,elGeo:{elHeight:f,elWidth:g,foldTop:s.cumulRect.top,totalArea:s.parentArea},rect:e.rect}}f=a.d.e(e,d);e.isVisible=e.percv>=f;e.elGeo&&(e.elGeo.threshold=f);return e};a.d.e=function(b,d){return b.area>=a.d.c?(d.viewstats.isBigAd=!0,a.d.b):a.d.a};a.d.f=function(){return g};a.d.g=function(a,b){g&&f.hasOwnProperty(b)||h(a);return f[b]};a.d.i=function(a){var b,d,c,e=0,f=0;try{b=a.document,d=b.documentElement,c=b.body}catch(s){return{width:e,height:f,left:0,right:e,top:0,
bottom:f}}"undefined"!==typeof a.innerWidth?(e=a.innerWidth,f=a.innerHeight):"CSS1Compat"===b.compatMode&&5!==b.documentMode||!c||"undefined"===typeof c.clientWidth?d&&"undefined"!==typeof d.clientWidth&&(e=d.clientWidth,f=d.clientHeight):(e=c.clientWidth,f=c.clientHeight);return{width:e,height:f,left:0,right:e,top:0,bottom:f}};a.d.h=function(b,d,c){this.rect=c||b.getBoundingClientRect();c=["left","right","top","bottom"];for(var e=0;e<c.length;e++){var f=c[e];this[f]=this.rect[f]}this.width=this.right-
this.left;this.height=this.bottom-this.top;this.el=b;this.win=d||b&&a.e.a(b);this.changeReferenceFrame=function(a){this.left+=a.left;this.right+=a.left;this.top+=a.top;this.bottom+=a.top};this.calcArea=function(){return(this.right-this.left)*(this.bottom-this.top)};this.getViewportRect=function(b){var d=a.d.i(this.win);b&&(b.width<d.width&&(d.width=b.width,d.right=d.left+d.width),b.height<d.height&&(d.height=b.height,d.bottom=d.top+d.height));return d}};a.d.j=function(b,c){var e=d(b.left,b.right,
c.left,c.right),f=d(b.top,b.bottom,c.top,c.bottom);return new a.d.h(void 0,void 0,{left:e[0],right:e[1],top:f[0],bottom:f[1]})}})(m);(function(a){function k(b){a.focus.pageIsVisible(!0)&&((new q).getTime()-f>=B&&e?(a.f.k(),a.f.i(t[H])):n||(n=!0,a.c.e(function(){n=!1;k()},s)))}function h(){a.f.o=(new q).getTime();a.c.f(function(){var b=d.getElementById("moatPx"+H),s=d.getElementById("moatPxEmbed"+H);c(b)?(e=b,g=b.parentNode):c(s)&&(e=s,g=b.parentNode);if(!1!==e){a.f.g?a.f.d=e.setConfig(w):a.f.f?a.f.d=
e.setConfig(w):e.setConfig(R);a.f.b&&(a.f.b="off"===a.f.d);if(8===l&&"iescope"===a.f.d){var f=function(){try{var b=parseInt(e.style.top,10);e.style.top=0>b?b+1E4+"px":b-1E4+"px";a.c.e(f,100)}catch(d){}};a.c.e(f,16)}return!0}},y,P)}function c(a){try{return a&&(a.getStats||"undefined"!==typeof a.getStats||a.getStats())&&!0}catch(b){return!1}}function b(a,b,d){var c=document.createElement("param");c.setAttribute("name",b);c.setAttribute("value",d);a.appendChild(c)}a.f={};a.f.a=function(){function a(b){b=
b.match(/[\d]+/g);b.length=3;return b.join(".")}var b=!1,d="";if(navigator.plugins&&navigator.plugins.length){var c=navigator.plugins["Shockwave Flash"];c&&(b=!0,c.description&&(d=a(c.description)));navigator.plugins["Shockwave Flash 2.0"]&&(b=!0,d="2.0.0.11")}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(b=(c=navigator.mimeTypes["application/x-shockwave-flash"])&&c.enabledPlugin)&&(d=a(c.enabledPlugin.description));else try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=!0,d=
a(c.GetVariable("$version"))}catch(e){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b=!0,d="6.0.21"}catch(s){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=!0,d=a(c.GetVariable("$version"))}catch(f){}}}return b?d:"0"}();a.f.b=!1;a.f.c="";a.f.d="default";var d,e=!1,g,f=0,n=!1,l=a.a.e(),u=null!==l,A=-1!==navigator.userAgent.indexOf("Chrome"),m=6.2<=function(){var a=navigator.appVersion.match(/Windows NT (\d\.\d)/);return a?parseFloat(a[1]):-1}(),B=1E3,s=200,K=a.b.protocol+"//"+
a.b.j,H=!1;a.f.e=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.f.f=!1;a.f.g=!1;var R={"default":{targetVersion:"*",lo:""}},w={iescope:{targetVersion:"*",lo:">="}};try{var z=a.a.e();if(7==z||8==z||9==z||10==z||11==z)a.f.g=!0}catch(r){}var P=10,y=500,x=!0,D;a.f.h=function(){if(e&&e.getStats)try{"iescope"===a.f.d&&(x&&(x=!1,D=e.style.width),e.style.width=D!==e.style.width?D:parseInt(D,10)+1+"px");var b=e&&e.getStats();if(b&&b.ok)return"off"!==a.f.d&&(a.f.b=!0),a.f.c=b.rev,
b}catch(d){}return!1};a.f.i=function(c){if(a.f.j()){var e=c.zr;try{var s=K+"/swf/p5.v1e.swf",g,n;n=u?g=2:g=1;var A=a.d.g(c,e),w="position: absolute; width: "+g+"px; height: "+n+"px; z-index: -9999;";a.f.f&&(w+="-webkit-transform: translate3d(0, 0, 0);");var z=w+"left: "+A.absLeft+"px; top: "+(A.absTop+A.height/2)+"px;",w=w+"left: 0px; top: 0px;";c.ed.x=A.absLeft;c.ed.y=A.absTop;A="ym"+e;H=e;v.yl||(v.yl={});v.yl[A]=function(){h()};var B=c.aa.ownerDocument;("defaultView"in B?B.defaultView:B.parentWindow)[a.b.d]=
v;var R="ol="+a.b.d+".yl."+A+"&db=false";d=B;if(m&&u&&10<=l)var r=function(){var a="moatPx"+e,d=B.createElement("OBJECT");d.setAttribute("data",s);d.setAttribute("id",a);d.setAttribute("name",a);d.setAttribute("style",z);d.setAttribute("width",g+"");d.setAttribute("height",n+"");b(d,"flashvars",R);b(d,"wmode","transparent");b(d,"bgcolor","");b(d,"allowscriptaccess","always");var a=B.body,c=B.createElement("div");c.id="moatPxDiv"+e;c.style.width="0px";c.style.height="0px";a.insertBefore(c,a.firstChild);
c.appendChild(d);return!0};else var t='<object type="application/x-shockwave-flash" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="'+g+'" height="'+n+'" style="'+z+'" id="moatPx'+e+'"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+s+'" /><param name="quality" value="low" /><param name="hasPriority" value="true" /><param name="FlashVars" value="'+
R+'" /><param name="bgcolor" value="" /><param name="wmode" value="transparent" /><embed type="application/x-shockwave-flash" src="'+s+'" quality="low" flashvars="'+R+'" bgcolor="" wmode="transparent" width="'+g+'" height="'+n+'" id="moatPxEmbed'+e+'" name="moatPx'+e+'" style="'+w+'" hasPriority="true" allowscriptaccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" /></object>',r=function(){var b=B.createElement("div");b.id=
"moatPxDiv"+e;b.style.width="0px";b.style.height="0px";if(!0===a.a.q(b,d)){b.innerHTML=t;try{b.getElementsByTagName("object")}catch(c){}return!0}return!1};f=(new q).getTime();a.c.f(r,10,100);m&&u&&10<=l&&a.focus.supportsPageVisAPI()&&a.c.b(d,a.focus.visibilitychange,k,e)}catch(P){}}};a.f.l=function(b,d){var c=a.f.m,e=b.aa.ownerDocument.getElementById("moatPx"+d);if(e){var s=e.parentNode;if(0!==s.id.indexOf("moatPxDiv")){var f=document.getElementById("moatPxDiv"+d);s.removeChild(e);f.appendChild(e)}s=
a.d.g(b,d);s={left:s.absLeft+s.width/2,top:s.absTop+s.height/2};c(s,b.ed)&&(e.style.left=s.left+"px",e.style.top=s.top+"px",b.ed.x=s.left,b.ed.y=s.top)}};a.f.k=function(){g&&g.parentNode&&(a.c.c(d,a.focus.visibilitychange,k,H),e.parentNode.removeChild(e),g.parentNode.removeChild(g),d=g=e=!1)};a.f.n=function(b){a.f.l(b,b.zr);isVisible=(b=a.f.h())?b.iv:!1;return{isVisible:isVisible}};a.f.j=function(){return u||a.b.k&&!a.b.l&&A||a.f.f};a.f.m=function(a,b){return a&&(a.left!==b.x||a.top!==b.y)}})(m);
(function(a){function k(a,b,d){a.IR5.MIN[d]=r.min(b,a.IR5.MIN[d])||b||1;a.IR5.MAX[d]=r.max(b,a.IR5.MAX[d])||b}function h(a,b){b.be=r.max("undefined"!==typeof b.be?b.be:0,a-b.bf);"undefined"===typeof b.by&&b.be>=B&&(b.by=b.bk)}function c(b){b.az===a.g.a.d.a?b.az=a.g.a.d.b:b.az===a.g.a.d.b&&(b.az=a.g.a.d.a)}function b(b){b.ba===a.g.a.d.a?b.ba=a.g.a.d.b:b.ba===a.g.a.d.b&&(b.ba=a.g.a.d.a)}function d(b){b.ax===a.g.a.b.a?b.ax=a.g.a.b.b:b.ax===a.g.a.b.b&&(b.ax=a.g.a.b.a)}function e(b){b.ay===a.g.a.c.a?b.ay=
a.g.a.c.b:b.ay===a.g.a.c.b&&(b.ay=a.g.a.c.a)}function g(a,b){"undefined"===typeof b.bk&&(b.bk=0);b.bk+=a-b.bo;b.bo=a}function f(a,b){"undefined"===typeof b.bl&&(b.bl=0);b.bl+=a-b.bp;b.bp=a}function n(a,b){"undefined"===typeof b.bg&&(b.bg=0);"undefined"===typeof b.bc&&(b.bc=0);b.bu=a-b.bs;b.bu>b.bc&&(b.bc=b.bu);b.bg+=a-b.bq;b.bc>=m&&"undefined"===typeof b.bw&&(b.bk+=a-b.bo,b.bw=b.bk);b.bq=a}function l(a,b){"undefined"===typeof b.bh&&(b.bh=0);"undefined"===typeof b.bd&&(b.bd=0);b.bv=a-b.bt;b.bv>b.bd&&
(b.bd=b.bv);b.bh+=a-b.br;b.bd>=m&&"undefined"===typeof b.bx&&(b.bl+=a-b.bp,b.bx=b.bl);b.br=a}a.g={};var u=500,A=3E3,m=500,B=500;a.g.a={};a.g.a.a={};a.g.a.a.a=0;a.g.a.a.b=1;a.g.a.b={};a.g.a.b.a=0;a.g.a.b.b=1;a.g.a.c={};a.g.a.c.a=0;a.g.a.c.b=1;a.g.a.d={};a.g.a.d.a=0;a.g.a.d.b=1;a.g.a.e={};a.g.a.e.a=0;a.g.a.e.b=1;a.g.a.f={};a.g.a.f.a=0;a.g.a.f.b=1;a.g.a.f.c=2;a.g.b=function(a){k(a,a.aj,"x");k(a,a.ak,"y");a.IR5.AREA=(a.IR5.MAX.x-a.IR5.MIN.x)*(a.IR5.MAX.y-a.IR5.MIN.y)};a.g.c=function(b){function d(){(new q).getTime()-
O>=u&&(a.g.d({type:"park"},b),clearInterval(e),b.au=a.g.a.a.a)}var c=b.au;if(c===a.g.a.a.a){O=(new q).getTime();var e=a.c.d(d,50);b.au=a.g.a.a.b}else c===a.g.a.a.b&&(O=(new q).getTime())};a.g.e=function(b){function d(){(new q).getTime()-S>=A&&(a.g.f({type:"park"},b),clearInterval(e),b.av=a.g.a.a.a)}var c=b.av;if(c===a.g.a.a.a){S=(new q).getTime();var e=a.c.d(d,50);b.av=a.g.a.a.b}else c===a.g.a.a.b&&(S=(new q).getTime())};a.g.g=function(b,d){var e=b.type;if(d.az===a.g.a.d.a){if("mouseover"===e||"mousemove"===
e)d.bo=(new q).getTime(),c(d)}else if(d.az===a.g.a.d.b){"mousemove"===e&&g((new q).getTime(),d);if("mouseout"===e||"blur"===e)g((new q).getTime(),d),c(d);"scooper"===e&&g((new q).getTime(),d)}};a.g.h=function(d,c){var e=d.type;if(c.ba===a.g.a.d.a){if("mouseover"===e||"mousemove"===e)c.bp=(new q).getTime(),b(c)}else if(c.ba===a.g.a.d.b){"mousemove"===e&&f((new q).getTime(),c);if("mouseout"===e||"blur"===e)f((new q).getTime(),c),b(c);"scooper"===e&&f((new q).getTime(),c)}};a.g.d=function(b,c){if(2!=
c.an){var e=b.type;if(c.ax===a.g.a.b.a){if("mouseover"===e||"mousemove"===e)c.bq=(new q).getTime(),c.bs=(new q).getTime(),d(c)}else c.ax===a.g.a.b.b&&("mousemove"!==e&&"mouseout"!==e||n((new q).getTime(),c),"park"===e&&n((new q).getTime()-u,c),"mouseout"!==e&&"park"!==e||d(c))}};a.g.f=function(b,d){if(2!=d.an){var c=b.type;if(d.ay===a.g.a.c.a){if("mouseover"===c||"mousemove"===c)d.br=(new q).getTime(),d.bt=(new q).getTime(),e(d)}else d.ay===a.g.a.c.b&&("mousemove"!==c&&"mouseout"!==c||l((new q).getTime(),
d),"park"===c&&l((new q).getTime()-A,d),"mouseout"!==c&&"park"!==c||e(d))}};a.g.i=function(b,d){var c=b.type;if(d.bb==a.g.a.e.a){if("mouseover"==c||"mousemove"==c)d.bf=(new q).getTime(),d.bb=a.g.a.e.b}else d.bb==a.g.a.e.b&&("mouseout"==c?(h((new q).getTime(),d),d.bb=a.g.a.e.a):"mousemove"!=c&&"scooper"!=c||h((new q).getTime(),d))}})(m);(function(a){function k(b){if(!a.focus.pageIsPrerendered()){a.c.c(document,n,k,"pr");for(var d in t)t.hasOwnProperty(d)&&a.e.c(t[d])}}function h(a){"undefined"==typeof e&&
(e=a)}a.focus={};var c=navigator.userAgent,c=-1<c.indexOf("Safari")&&-1==c.indexOf("Chrome")&&-1==c.indexOf("Chromium")&&!D,b=(eval("/*@cc_on!@*/false")||document.documentMode)&&!D,d="undefined"!==typeof document.hasFocus,e,g={visible:0,hidden:1,prerender:2},f,n,l,u;"undefined"!==typeof document.hidden?(f="hidden",n="visibilitychange"):"undefined"!==typeof document.mozHidden?(f="mozHidden",n="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(f="msHidden",n="msvisibilitychange"):"undefined"!==
typeof document.webkitHidden&&(f="webkitHidden",n="webkitvisibilitychange");for(var A=["v","mozV","msV","webkitV"],m=0;m<A.length;m++){var B=A[m]+"isibilityState";if("undefined"!==typeof document[B]){l=B;break}}u="undefined"!==typeof f;var s,K;"undefined"!==typeof window.requestAnimationFrame?s="requestAnimationFrame":"undefined"!==typeof window.webkitRequestAnimationFrame&&(s="webkitRequestAnimationFrame");K=c&&"string"==typeof s&&!u;var H=(new q).getTime();K&&function z(){H=(new q).getTime();window[s](z)}();
a.focus.getFocusMethod=function(){return e};a.focus.visibilitychange=n;a.focus.setFocusListeners=function(){"Microsoft Internet Explorer"===navigator.appName?(a.c.b(x.document,"focusout",function(){v.yd()},!1),a.c.b(x.document,"focusin",function(){v.ye()},!1)):(a.c.b(x,"blur",function(){v.yd()},!1),a.c.b(x,"focus",function(){v.ye()},!1))};a.focus.getQueryString=function(a){a={};a.em=e;r&&(a.eo=1);"undefined"!=typeof l&&(a.en=g[document[l]]);return a};a.focus.supportsPageVisAPI=function(){return u};
a.focus.pageIsVisible=function(){if(a.focus.supportsPageVisAPI())return h(0),!document[f];if(K)return h(1),100>(new q).getTime()-H;if(b&&d)return h(2),document.hasFocus();h(3);return!0};a.focus.pageIsPrerendered=function(){return"undefined"!==typeof l?"prerender"==document[l]:!1};a.focus.pageIsVisible();a.focus.pageIsPrerendered()&&a.c.b(document,n,k,"pr");var r=a.focus.pageIsPrerendered();a.focus.windowHasFocus=function(){return v.v}})(m);(function(a){function k(b,d,c,e,f){("remove"===f?a.c.c:a.c.b)(b,
d,function(d){d=d||this.event;var e=d.currentTarget||b,f=t[e[T]];if(f){var g;g=d;var n=e.getBoundingClientRect();g=-1!=g.type.indexOf("touch")?{x:parseInt(g.changedTouches[0].clientX-n.left,10),y:parseInt(g.changedTouches[0].clientY-n.top,10)}:{x:parseInt(g.clientX-n.left,10),y:parseInt(g.clientY-n.top,10)};f.aj=g.x;f.ak=g.y;f.dm||(f.cb=2==a.focus.getFocusMethod()?f.counters.laxDwell.tCur:f.counters.strictDwell.tCur,f.dm=1);c.call(b,d,e,f)}},e)}function h(a,e,f){k(a,"click",u,e,f);k(a,"mousedown",
b,e,f);D?k(a,"touchstart",d,e,f):(k(a,"mousemove",c,e,f),k(a,"mouseover",n,e,f),k(a,"mouseout",l,e,f))}function c(b,d,c){D||c.aj===c.al&&c.ak===c.am||(a.g.d(b,c),a.g.f(b,c),a.g.g(b,c),a.g.i(b,c),a.g.h(b,c),a.g.b(c),a.g.c(c),a.g.e(c),0===c.ar.length&&(c.ai=m(c)),c.ar.push(c.aj),c.as.push(c.ak),c.at.push(a.a.h(c)),c.al=c.aj,c.am=c.ak);c.ai!==m(c)&&1<c.ar.length&&A(c,"onMouseMove")}function b(b,d,c){b={e:2};b.q=c.aq[2]++;b.x=c.aj;b.y=c.ak;a.i.a(c,b)}function d(b,d,c){b={e:23};b.q=c.aq[23]++;b.x=c.aj;
b.y=c.ak;d=(new q).getTime();if("undefined"===typeof c.ct)c.ct=d;else{var e=d-c.ct;c.ct=d;c.cu=r.min(c.cu,e)||e}b.bz=void 0;a.i.a(c,b)}function e(b,c,d){if(2==b.an){var e=c.e,n=b.ck;n==a.g.a.f.a&&6===e?(g(b,0),b.cl=a.a.h(b),b.ck=a.g.a.f.b):n==a.g.a.f.b?22===e?(f(b,c),g(b,d),b.cl=a.a.h(b)):7===e&&(1E3<a.a.h(b)-b.cl?(clearTimeout(b.cm),c.e=22,f(b,c),b.cn=0,b.ck=a.g.a.f.a):b.ck=a.g.a.f.c):n==a.g.a.f.c&&(6==e?(1E3<a.a.h(b)-b.cl&&(clearTimeout(b.cm),b.cn=0,b.cl=a.a.h(b),g(b,0)),b.ck=a.g.a.f.b):22==e&&
(f(b,c),b.ck=a.g.a.f.a,b.cn=0))}}function g(b,c){var d=5>b.cn?1E3:2*c,f={e:22};b.cm=a.c.e(function(){e(b,f,d)},d)}function f(b,c){c.q=b.aq[c.e]++;c.m=a.a.h(b);b.cl=c.m;a.i.a(b,c);b.cn++}function n(b,c,d){a.g.d(b,d);a.g.f(b,d);a.g.g(b,d);a.g.i(b,d);a.g.h(b,d);e(d,{e:6},0)}function l(b,c,d){a.g.d(b,d);a.g.f(b,d);a.g.g(b,d);a.g.i(b,d);a.g.h(b,d);e(d,{e:7},0)}function u(b,d,c){b={e:3};b.q=c.aq[3]++;b.x=c.aj;b.y=c.ak;a.i.a(c,b)}function A(b,c){b.ai=m(b);var d={e:1};d.q=b.aq[1]++;d.x=b.ar.join("a");d.y=
b.as.join("a");for(var e=a.a.h(b),f=b.at,g=[],n=0;n<f.length;n++)isNaN(f[n])||g.push(r.abs(f[n]-e));d.c=g.join("a");d.m=e;a.i.a(b,d);b.ar=[];b.as=[];b.at=[]}function m(b){return r.floor(a.a.h(b)/B)}a.h={};var B=1E3;a.h.a=function(a,b){if(!0===a.isSkin)for(var d=0;d<a.elements.length;d++)h(a.elements[d],a.zr+"-"+d,b);else h(a.aa,a.zr,b)};a.h.b=function(b){for(var d in t)t.hasOwnProperty(d)&&(b=t[d])&&(a.g.g({type:"scooper"},b),a.g.i({type:"scooper"},b),a.g.h({type:"scooper"},b),1<b.ar.length&&b.ai!==
m(b)&&A(b,"scooper"))}})(m);(function(a){a.j={};var k="undefined"!==typeof window.devicePixelRatio,h=k&&r.round(1E3*window.devicePixelRatio),c=a.b.a&&k&&"undefined"!==typeof window.innerHeight&&"undefined"!==typeof window.outerHeight&&r.round(window.devicePixelRatio*(a.b.c.outerHeight-a.b.c.innerHeight)),b="undefined"!==typeof window.mozInnerScreenX&&"undefined"!==typeof window.screenX;a.j.a=function(b,c){var g;try{var f,n=b.aa.getBoundingClientRect(),l=c||b.WINDOW||a.e.a(b.aa),u=a.d.i(l),h=a.d.j(n,
u),m=l.mozInnerScreenX,q=l.mozInnerScreenY,s=window.screenX,r=window.screenY,t=a.d.j({left:h.left+m,right:h.right+m,top:h.top+q,bottom:h.bottom+q},{left:s,right:s+window.outerWidth,top:r+117/(k?window.devicePixelRatio:1),bottom:r+window.outerHeight}),v=n.width*n.height;f={area:v,percv:(t.right-t.left)*(t.bottom-t.top)/v};var w=a.d.e(f,b);g=f.percv>=w}catch(z){g=!1}return{isVisible:g}};a.j.b=function(){return b};a.j.c=function(){var a={};a.dl=Number(b);"number"!==typeof h||isNaN(h)||(a.dm=h);"number"!==
typeof c||isNaN(c)||(a.dn=c);return a}})(m);(function(a){function k(a){var b=0,g;return function(){var f=(new q).getTime();f-b>c&&(g=a.apply(this,arguments),b=f);return g}}function h(b,c,g,f){var n=0,l=0,u=0,h=(new q).getTime(),k=!1,m=!1,s,t,v,y=0,w=0,z=0,x=0,P=!1,D=a.b.a,F;if(0===f)var C="as",E="ag",J="an",L="ck",M="kw",N="ah",O="aj",S="pg",T="pf",P=!0;else 1===f?(C="cc",E="bw",J="bx",L="ci",M="jz",N="bu",O="dj"):2===f&&(C="cg",E="ce",J="cf",L="cj",M="ts",N="ah",O="dk");this.hadOTS=function(){return m};
this.hadVideo2SecOTS=function(){return _hadVideo2SecOts};this.getInViewTime=function(){return n};this.visible=function(){return k};this.update=function(l){var x=!1,G=b(l);l.elementRect=G.rect;var Q=G.isVisible,C=c(l),E=(new q).getTime(),I=r.max(r.min(E-h,1E3),0);h=E;E=!g||a.focus.pageIsVisible(2===f);if((Q=Q&&E&&!C)&&k)n+=I,u+=I;else if(Q||k)I=r.round(I/2),n+=I,u+=I;!m&&1E3<=u&&(x=m=!0,t=n,this.timeToView=s=l.counters.query()[N]);"undefined"===typeof v&&(1E3>=l.counters.query().bu?Q&&(v=!0):v=!1);
if((l.FOLDMEASURABLE=D)&&"undefined"===typeof F&&2!==f&&G.elGeo){var I=a.b.c,C=I.document,J=G.elGeo.threshold*G.elGeo.elHeight;_isBTFCheck=(void 0!==I.pageYOffset?I.pageYOffset:(C.documentElement||C.body.parentNode||C.body).scrollTop)+G.elGeo.foldTop>a.k.a()-J;0<G.elGeo.totalArea&&(F=_isBTFCheck,l.BELOWTHEFOLDAD=F)}l=G.yMinMax;P&&E&&"undefined"!==typeof l&&G.elGeo&&0<=l.yMax&&0<=l.yMin&&0<G.visibleArea&&(y=r.max(l.yMax,y),w=r.min(l.yMin,w),z=r.min(1,r.max((y-w)/G.elGeo.elHeight,z)));Q||(u=0);k=Q;
return x};this.getQS=function(a){l>n&&(l=n);a[C]=Number(m);a[E]=n;a[J]=l;"undefined"!==typeof t&&(a[L]=t);"undefined"!==typeof s&&(a[M]=s);"undefined"!==typeof v&&(a[O]=Number(v));if(!0===P){var b=r.round(100*z),c=r.round(100*x);a[S]=b;a[T]=c;x=z}"undefined"!==typeof F&&(a.ib=Number(F));l=n}}a.k={};var c=150,b={};a.k.a=function(){return D?a.d.i(a.b.c).height:750};a.k.b=function(c){var e=c.zr;b[e]={};c.viewstats={isBigAd:!1};if(a.d.f()){var g=k(a.d.d),f;f=new h(g,a.e.d,!0,0);b[e].strict=f;g=new h(g,
a.e.d,!1,1);b[e].lax=g}!0!==c.isSkin&&a.j&&a.j.b()?(c=new h(a.j.a,a.e.d,!0,2),b[e].pscope=c):a.f&&a.f.j()&&(c=new h(a.f.n,a.e.d,!0,2),b[e].pscope=c)};a.k.c=function(c){var e=b[c.zr],g,f;for(f in e)e.hasOwnProperty(f)&&e[f].update(c)&&(g=!0);g&&a.e.e(c);a.l.a(c)&&a.e.f(c)};a.k.d=function(b,c,g){"unefined"==typeof g&&(g=!1);var f=a.k&&a.k.e(b.zr);b=(a.j&&a.j.b()||a.f&&a.f.b)&&f&&f.pscope.getInViewTime()>=c;c=g?a.d&&a.d.f()&&f&&f.strict&&f.strict.getInViewTime()>=c:a.d&&a.d.f()&&f&&f.lax&&f.lax.getInViewTime()>=
c;return a.b.a?c:b};a.k.f=function(a){delete b[a]};a.k.e=function(a){return b[a]};a.k.g=function(a){var c={},g=b[a],f;for(f in g)g.hasOwnProperty(f)&&g[f].getQS(c);(a=t[a])&&a.viewstats.isBigAd&&(c.el=1);return c}})(m);(function(a){a.m={};a.m.a=function(a,h){var c;h.outerHTML?c=h.outerHTML:(c=document.createElement("div"),c.appendChild(h.cloneNode(!0)),c=c.innerHTML);c=[/flashvars\s*=\s*(".*?"|'.*?')/i.exec(c),/name\s*=\s*["']flashvars["']\s*value\s*=\s*(".*?"|'.*?')/i.exec(c),/value\s*=\s*(".*?"|'.*?')\s*name\s*=\s*["']flashvars["']/i.exec(c),
a];for(var b,d,e={},g=0;g<c.length;g++){if((b=c[g])&&"object"===typeof b&&b[1])b=b[1].replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/^"/g,"").replace(/"$/g,"").replace(/^'/g,"").replace(/'$/g,"");else if("string"===typeof b)b=b.split("?")[1];else continue;if(b){b=b.split("&");for(var f=0;f<b.length;f++)d=b[f].split("="),2>d.length||"function"==d[0].slice(0,8)||(e[d[0]]=[d[1]])}}return e}})(m);(function(a){function k(b){var c={window:0,transparent:1,opaque:2,direct:3,gpu:4};if("EMBED"===b.tagName)var e=
a.a.getAttribute(b,"wmode");else if("OBJECT"===b.tagName){b=b.getElementsByTagName("param");for(var g=0;g<b.length;g++){var f=b[g],n=a.a.getAttribute(f,"name"),f=a.a.getAttribute(f,"value");if("wmode"===n){e=f;break}}}return e&&c[e.toLowerCase()]||5}function h(b){var d=b.el,e=b.url,g=b.flashVars,f=b.adIds,n=b.opt_props;(new q).getTime();this.ao=f;this.FIND_AD_TRIES=f.numTries||0;var l;try{if(d){var u=d,h;"DIV"===u.tagName&&((u=d.getElementsByTagName("EMBED")[0])||(u=d.getElementsByTagName("OBJECT")[0]),
u||(u=d.getElementsByTagName("IMG")[0]),u||(u=d));if("OBJECT"===u.tagName){for(var m=0;m<u.children.length;m++)if("movie"===u.children[m].name||"Movie"===u.children[m].name)h=u.children[m].value;u.object&&u.object.Movie?h=u.object.Movie:u.data&&-1!==u.data.indexOf("swf")&&(h=u.data)}"EMBED"!==u.tagName&&"IMG"!==u.tagName||!u.src||(h=u.src);var B=a.m.a(h,u);l={adURL:h,flashVars:B}}else l=!1}catch(s){l=!1}if(l&&l.adURL&&g)for(p in l.flashVars)l.flashVars.hasOwnProperty(p)&&(g[p]=l.flashVars[p]);l&&
l.flashVars&&(g=l.flashVars);if("string"!==typeof e||"DIV"===e)e=l&&l.adURL||"-";e&&0!==e.toLowerCase().indexOf("http:")&&0!==e.toLowerCase().indexOf("https:")&&("/"===e[0]?e=window.location.protocol+"//"+window.location.host+e:(l=window.location.pathname.split("/").slice(0,-1).join("/"),e=window.location.protocol+"//"+window.location.host+"/"+l+(l?"/":"")+e));"IFRAME"!==d.tagName&&"IMG"!==d.tagName&&-1===e.indexOf("googlesyndication")&&(e=e.split("?")[0]);this.zr=f.adNum;t[this.zr]=this;a.l.d(this.zr,
[d]);this.ae=e;this.aa=d;this.WINDOW=a.e.a(this.aa);this.INITIAL_WIDTH=d.offsetWidth;this.INITIAL_HEIGHT=d.offsetHeight;"undefined"===typeof g&&(g={});v.i[E]=!0;this.eg=[];this.ee={};n&&n.IS_PAGE_LEVEL||(this.ed={},a.f.i(this));a.e.g(this);this.ag=g;this.ah=void 0;this.ai=0;this.an=this.am=this.al=this.ak=this.aj=void 0;this.ar=[];this.as=[];this.at=[];this.av=this.au=a.g.a.a.a;this.ax=a.g.a.b.a;this.ay=a.g.a.c.a;this.ba=this.az=a.g.a.d.a;this.bb=a.g.a.e.a;this.by=this.bx=this.bw=this.bv=this.bu=
this.bt=this.bs=this.br=this.bq=this.bp=this.bo=this.bm=this.bl=this.bk=this.bi=this.bh=this.bg=this.bf=this.be=this.bd=this.bc=void 0;this.ca=this.bz=!1;this.cb=this.cu=this.ct=void 0;this.cc=+new q+12E4;this.BEACON_LAST_SENT_AT=+new q;this.cl=this.cm=void 0;this.cn=0;this.ck=a.g.a.f.a;this.cd=!1;this.cy=void 0;this.dt=!1;this.db=void 0;this.cf=this.ce=!1;this.af=Number(this.ef);this.eq=!1;this.ds=this.ch=this.dr=this.cg=0;this.dq=this.bn=void 0;this.IR5={MIN:{x:void 0,y:void 0},MAX:{x:void 0,y:void 0},
AREA:0};a.k.b(this);this.dm=0;this.ep=this.dd=!1;this.aq={};this.aq.g=0;this.aq[1]=0;this.aq[2]=0;this.aq[3]=0;this.aq[13]=0;this.aq[0]=0;this.aq[4]=0;this.aq[5]=0;this.aq[6]=0;this.aq[7]=0;this.aq[9]=0;this.aq[8]=0;this.aq[15]=0;this.aq[16]=0;this.aq[21]=0;this.aq[22]=0;this.aq[23]=0;this.INVIEW_TIME_THRESHHOLDS=[5,10,15,30,60];this.DWELL_TIME_THRESHHOLDS=[5,10,15,30,60];this.an=b.adType||c(d);0===this.an&&(this.WMODE=k(d));a.l.c(this)}function c(a){return"IFRAME"===a.tagName?2:"IMG"===a.tagName?
1:"EMBED"===a.tagName||"OBJECT"===a.tagName?0:3}a.l={};a.l.b=function(b,d,e,g,f,n,l){var u;u=1==arguments.length?arguments[0]:{el:b,url:d,flashVars:g,adIds:f,opt_props:l};if(n){if("function"===typeof n)return n(b,d,g,f);new q;n.em=!0;t[n.zr]=n;b[T]=n.zr;b[y]=!0;n.aa=b;n.INITIAL_WIDTH=b.offsetWidth;n.INITIAL_HEIGHT=b.offsetHeight;n.ae=d;n.an=c(b);0===n.an&&(n.WMODE=k(b));n.ag=g||{};a.h.a(n);u={e:0};u.q=n.aq[0]++;a.i.a(n,u);return n}return new h(u)};a.l.c=function(b){b.de=b.ao.startTime;b.RAND=b.ao.rand;
(new q).getTime();b.dd=!0;a.k.c(b);var c={e:0};c.q=b.aq[0]++;a.i.a(b,c);a.h.a(b)};a.l.a=function(b){var c=+new q,e=c-b.BEACON_LAST_SENT_AT;if(0<b.DWELL_TIME_THRESHHOLDS.length){var g=1E3*b.DWELL_TIME_THRESHHOLDS[0];if(b.counters.strictDwell.tCur>=g){b.DWELL_TIME_THRESHHOLDS.shift();var f=b.INVIEW_TIME_THRESHHOLDS.length?b.INVIEW_TIME_THRESHHOLDS[0]:60;if(g<f)return!1;if(5E3<e)return!0}}return 0<b.INVIEW_TIME_THRESHHOLDS.length&&(f=1E3*b.INVIEW_TIME_THRESHHOLDS[0],a.k.d(b,f))?(b.INVIEW_TIME_THRESHHOLDS.shift(),
!0):0===b.DWELL_TIME_THRESHHOLDS.length&&c>b.cc?(b.cc*=2,!0):!1};a.l.d=function(a,c){for(var e=0;e<c.length;e++){var g=c[e];g[T]=a;g[y]=!0}}})(m);(function(a){function k(b,c,g){if(!b)return!1;for(var f=b.getElementsByTagName("DIV"),n=0;n<f.length;n++){var l=f[n];if(l.id&&-1<l.id.indexOf("pickleads_wrapper")){var h=l.offsetHeight;if(1<l.offsetWidth&&1<h&&(l=a.l.b(l,"DIV",!1,void 0,c,g)))return l}}n=a.a.e();f=null!==n&&11>n;if(!f)for(l=b.getElementsByTagName("embed"),n=0;n<l.length;n++)if(h=l[n],!0!==
h[y]&&-1===h.id.indexOf("moatPx")&&a.a.o(h)&&h.getAttribute("src")){var k=h.getAttribute("src");b=a.m.a(k,h);return a.l.b(h,k,!1,b,c,g)}h=b.getElementsByTagName("object");for(n=0;n<h.length;n++)if(l=h[n],a.a.o(l)&&("undefined"===typeof l[y]||!0!==l[y])&&-1==l.id.indexOf("moatPx")){for(b=0;b<l.children.length;b++)if("movie"===l.children[b].name||"Movie"===l.children[b].name)for(k=l.children[b].value,n=0;n<l.children.length;n++){if(!f&&"EMBED"===l.children[n].tagName){h=l.children[n];if("undefined"!==
typeof h[y]&&!0===h[y]||-1!=h.id.indexOf("moatPx"))continue;if(a.a.o(h))return b=a.m.a(k,h),a.l.b(h,k,!1,b,c,g)}if("OBJECT"===l.children[n].tagName&&(h=l.children[n],a.a.o(h)&&!0!==h[y]&&-1===h.id.indexOf("moatPx")))return a.l.b(h,void 0,!1,void 0,c,g)}l.object&&l.object.Movie?k=l.object.Movie:l.data&&(k=l.data);b=a.m.a(k,l);return a.l.b(l,k,!1,b,c,g)}if(l=a.n.g(b,c,g))return l;k=b.getElementsByTagName("img");for(n=0;n<k.length;n++)if(f=k[n],"undefined"===typeof f[y]||!0!==f[y]){if(a.a.o(f)&&""!==
f.src&&-1===document.location.href.indexOf(f.src))return f.id&&-1<f.id.indexOf("checkm8")&&f.src&&-1<f.src.indexOf("transparent_pixel.png")?(b.MOATCHECKM8ORIGIN=!0,!1):a.l.b(f,f.getAttribute("src"),!1,void 0,c,g);J["1"]=f.offsetWidth+"x"+f.offsetHeight+":"+f.src}if(k=b.getElementsByTagName("canvas")[0])if(c=a.l.b(k.parentNode,k.parentNode.nodeName,!1,void 0,c,g))return c;return!1}function h(d,e){for(var g=[],f=d.getElementsByTagName("iframe"),h,l=0;l<f.length;l++)if(h=f[l],!h[y]&&a.a.o(h)){var k=
a.o.b(h)?!1:!0;(e===c&&k||e===b&&!k)&&g.push(h)}return g}a.n={};var c=1,b=2;a.n.a=function(b,c,g,f,h){var l=a.n.b,k=0;a.c.f(function(){c.numTries=k++;return l(b,c,g,f)&&!0},a.n.c,500,h)};a.n.g=function(b,e,g){b=h(b,c);if(b[0])return a.l.b(b[0],b[0].src,!1,void 0,e,g)};a.n.f=function(b,c,g){var f;b=a.n.e(b,a.n.h);for(var h=0;h<b.length;h++)if(f=b[h],f=a.o.b(f))if(f=k(f.documentElement,c,g))return f};a.n.i=function(b,c,g){var f,h;b=a.n.e(b,a.n.h);for(var l=0;l<b.length;l++)if(h=b[l],h=a.o.b(h)){if(f=
h.getElementById("flite-1"))if(f=a.l.b(f,f.nodeName,!1,void 0,c,g))return f;if(f=k(h.documentElement,c,g))return f}};a.n.d=k;a.n.b=function(b,c,g,f){var h=a.n.d;if("undefined"===typeof b)return!1;if("HEAD"===b.tagName){var l=b.parentNode;"HTML"===l.tagName&&(l=l.getElementsByTagName("body"),0<l.length&&(b=l[0]))}if((l=h(b,c,g))||(l=a.n.f(b,c,g)))return l;try{if(da&&F){var k=a.o.a(b),m;a:{var q=k.ownerDocument.getElementById("checkm8Cont_0");if(null===q)m=null;else{for(var t=q,s=0;(t=t.parentElement)&&
10>s;)if(s++,"TopAd"==t.id){m=q;break a}m=void 0}}if("TopAd"==k.id&&null!==m&&(l=a.l.b(m,m.nodeName,!1,void 0,c,g)))return l}}catch(v){}if((ea||f)&&(f=f||a.o.a(b))&&(!a.b.a||"BODY"!==f.nodeName||a.e.a(f)!=a.b.c)&&(l=h(f,c,g)))return l;b=b.getElementsByTagName("DIV");for(f=0;f<b.length;f++)if(k=b[f],k.id&&-1<k.id.indexOf("checkm8")&&(m=k.offsetHeight,k=k.offsetWidth,1<k&&1<m)){a:{q=document.getElementsByTagName("DIV");for(l=0;l<q.length;l++)if(t=q[l],t.id&&-1<t.id.indexOf("checkm8Cont")&&!0!==t.MOATCHECKM8ORIGIN){var r=
t.style;if(r&&(s=r.width,r=r.height,s&&r&&-1<s.indexOf(k)&&-1<r.indexOf(m))){k=t;break a}}k=!1}if(k){if(l=h(k,c,g))return l;break}}return!1};a.n.e=h;a.n.j=c;a.n.h=b;a.n.k=500;a.n.c=20;a.n.l={object:1,embed:1,img:1,iframe:1}})(m);(function(a){function k(c){try{if("string"===typeof c){c=c.toLowerCase();var b=c.split(".")[0];if(b&&a.a.f("travel travel2 theater theater2 homepage blogs health blog".split(" "),b)){if("travel2"===b||"theater2"===b||"blogs"===b)b=b.slice(0,-1);if("homepage"!==b&&"blog"===
b){var d=c.split("/");d[1]&&(b=d[2]?b+"-"+d[1]+("frontpage"===d[2]?"-SectionFront":"-Article"):b+"-"+d[1]+"-Other")}return b}var e=a.a.g("www.nytimes.com/yr/mo/day/ video.nytimes.com/video/playlist/ www.nytimes.com/top/news/ www.nytimes.com/archive/article/ www.nytimes.com/aponline/ www.nytimes.com/ref/ www.nytimes.com/slideshow/yr/mo/day/ global.nytimes.com/pages/ global.nytimes.com/yr/mo/day/ www.nytimes.com/interactive/yr/mo/day/ www.nytimes.com/pages/ prototype.nytimes.com/yr/mo/day/ ipad.nytimes.com/sectionfront/section/ ipad.nytimes.com/sectionfront/blogs/ ipad.nytimes.com/article/section/ ipad.nytimes.com/article/blog/ mraid.ipad/article/ mraid.ipad/sectionfront/ iphone.mobile.nytimes.com/yr/mo/day/ iphone.mobile.nytimes.com/pages/ mobile.nytimes.com/pages/ mobile.nytimes.com/yr/mo/day/ mweb.nytimes.com/yr/mo/day/ mweb.nytimes.com/pages/ www.nytimes.com/recommendations/".split(" "),
c);if(e){var g=c.split(e)[1],f=g.split("/")[0];if(f){var b=["ipad.nytimes.com","mraid.ipad"],d=["iphone.nytimes.com"],h=["mobile.nytimes.com","mweb.nytimes.com"];-1<c.indexOf("prototype.nytimes.com")?f="prototype-"+f:a.a.g(b,c)?f="iPadNewsApp-"+f:a.a.g(d,c)?f="iPhoneNewsApp-"+f:a.a.g(h,c)&&(f="MobileWeb-"+f);if(f.match(/blogs?/))var l=g.split("/"),f="directory.html"===l[l.length-1]?f+"-SectionFront":f+"-Other";else f=(isSectionFront=a.a.g(["/pages/","/sectionfront/","/frontpage"],e))?f+"-SectionFront":
f+"-Article";"www.nytimes.com/recommendations/"===e&&(f=-1!=f.indexOf("module")?"recommendations-"+f.split("-")[0]:"recommendations-"+f);return f}}}return"other"}catch(k){return"other"}}function h(a,b){for(var d={},e=a.split("&"),g=0;g<e.length;g++){var f=e[g].split("=");if("string"===typeof f[1]){var h=f,l,m=l=f[1];try{for(var q=0;100>q&&(l=decodeURIComponent(l),m!=l);q++)m=l}catch(t){}l=l.replace(/(^\s+|\s+$)/g,"");h[1]=l}else f[1]="";d[f[0]]=f[1]}d.parsedSection=k(d.moatClientSlicer1);d.zMoatVER&&
-1<d.zMoatVER.indexOf("nyt5")&&(d.parsedSection="nyt5-"+d.parsedSection);"undefined"!==typeof b&&(d.clientZone="undefined"!==b?b:"");return d}a.p={};a.p.a=function(a){"undefined"===typeof a.startTime&&(a.startTime=(new q).getTime());"undefined"===typeof a.rand&&(a.rand=r.floor(r.random()*r.pow(10,8)));a.adNum=v.zr;v.zr++};a.p.b=function(a){try{var b=a.className,d=a.getAttribute("src");b.split("\n").join(" ");if(-1!==b.indexOf("moatfooter"))return!1;var e=d.split("?");1==e.length&&(e=d.split("#"));
return 1<e.length?h(e[1],"undefined"):!1}catch(g){return!1}};a.p.c=function(a){try{var b=a&&a.className.replace("amp;","").split("?")[1];return b&&h(b)}catch(d){return!1}};a.p.d=function(a){try{var b=zoneRegEx.exec(a.innerHTML);0<b.length&&(zone=b[1]);return zone}catch(d){}};a.p.e=function(a){return(a=unescape(unescape(unescape(unescape(a.innerHTML)))).match(/~fdr=(\d*).*?\/.*?;(\d*)/))?{adid:a&&a[1]||"-",cid:a&&a[2]||"-"}:!1};a.p.f=function(a,b){return b||{}}})(m);(function(a){function k(c,b){var d,
e=[],g,f=a.a.d()?2048:7750,h=b||{};g={};for(d in c)c.hasOwnProperty(d)&&(1!=c.e||"x"!==d&&"y"!==d&&"c"!==d?e.push(encodeURIComponent(d)+"="+encodeURIComponent(c[d])):g[d]=c[d].split("a"));d=e.join("&");var e=f-d.length,l=0;if("undefined"!==typeof g.x){for(var k=0,m=0;m<g.x.length;m++)if(k+=g.x[m].length+(g.y[m]?g.y[m].length:0)+(g.c[m]?g.c[m].length:0),k<e)l++;else break;0<l&&(d+="&x="+g.x.slice(0,l-1).join("a"),d+="&y="+g.y.slice(0,l-1).join("a"),d+="&c="+g.c.slice(0,l-1).join("a"))}for(var q in h)h.hasOwnProperty(q)&&
(g="&"+encodeURIComponent(q)+"="+encodeURIComponent(h[q]),g.length+d.length<f&&(d+=g));return d}function h(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])}a.i={};a.i.b=function(c,b){a.p.a(b);var d={};d.e=c;d.i=L;if(11===c){var e=[],g;for(g in J)J.hasOwnProperty(g)&&e.push(g+"="+J[g]);d.k=e.join("&")}d.e in X||(d.bq=a.b.e,d.f=Number(!F),d.j=a.b.b,d.o=3,d.t=b.startTime,d.de=b.rand,d.m=0,d.ar=Y,a.a.u(d,"ai",v.z),d.q=v.m++,d.cb=D?1:0,d.cu=U,d.r=a.f.a,h(d,a.focus.getQueryString()),a.p.f(b,d),"undefined"!==
typeof b&&(d.d=b.moatClientLevel1+":"+b.moatClientLevel2+":"+b.moatClientLevel3+":"+b.moatClientLevel4,d.bd=b.parsedSection,d.zMoatSite=b.moatClientSlicer1,d.zMoatAT=b.zMoatAT||"-"),d.ac=1,d.it=a.n.k,d=k(d),v.yh.yi(d+"&cs=0",V,Z))};a.i.c=function(c){!0!==c.em&&(delete t[c.zr],clearTimeout(c.cc),a.n.a(C.parentNode,c.ao,c))};a.i.a=function(c,b){if(!c||!0===c.ep)return!1;if(!a.e.h(c))return a.e.i(c),!1;(3>c.aa.offsetHeight||3>c.aa.offsetWidth||!c.aa.parentNode)&&!1!==c.aa.findAgain&&a.i.c(c);if("undefined"!==
typeof c.ao&&(2!==c.an||1!==b.e&&3!==b.e)&&!(b.e in X)){b.lo=c.FIND_AD_TRIES;b.ak=c.ae;c.ah&&(b.a=c.ah);var d=c.ag,e={};if(9===b.e&&2===b.q||25===b.e){for(var g in d)d.hasOwnProperty(g)&&""!==g&&"undefined"!==typeof d[g]&&-1===g.indexOf("dvContains")&&-1===g.indexOf("indexOf")&&-1===g.toLowerCase().indexOf("clicktag")&&(e["z"+g]=d[g]);b.e=25}0===c.an&&(b.dc=c.WMODE);0!==b.e&&a.e.j(c);c.bi>c.bg&&(c.bg=c.bi);c.bm>c.bk&&(c.bk=c.bm);b.i=L;b.bq=a.b.e;b.g=c.aq.g++;d=c.INITIAL_WIDTH;b.h=c.INITIAL_HEIGHT;
b.w=d;b.f=Number(!F);b.j=a.b.b;b.o=3;b.t=c.de;b.de=c.RAND;b.cu=U;b.m=b.m||a.a.h(c);b.ar=Y;b.cb=D?1:0;b.r=a.f.a;h(b,a.j.c());a.j&&a.j.b()?b.ch=1:a.f&&a.f.b?(b.ch=1,b.ct=a.f.c,"undefined"!==typeof a.f.o&&c&&c.ao&&c.ao.startTime&&!isNaN(c.ao.startTime)&&(d=a.f.o-c.ao.startTime,b.fg=0<=d?d:0)):b.ch=0;h(b,a.k.g(c.zr));h(b,a.focus.getQueryString());h(b,c.counters.getQs());a.a.u(b,"ai",v.z);a.a.u(b,"ap",c.cb);a.a.u(b,"ax",c.bg);a.a.u(b,"ay",c.bi);a.a.u(b,"az",c.bk);a.a.u(b,"ba",c.bm);a.a.u(b,"aw",c.bc);
a.a.u(b,"bg",c.bd);a.a.u(b,"be",c.be);a.a.u(b,"bc",c.bw);a.a.u(b,"bf",c.by);a.a.u(b,"bh",c.bx);a.a.u(b,"bz",c.cu);b.cl=r.round(100*c.IR5.AREA/(b.w*b.h));b.au=c.aq[2]-1;b.av=c.aq[3]-1;b.by=c.aq[23]-1;b.at=c.dm;a.p.f(c.ao,b);b.d=c.ao.moatClientLevel1+":"+c.ao.moatClientLevel2+":"+c.ao.moatClientLevel3+":"+c.ao.moatClientLevel4;b.bd=c.ao.parsedSection;b.zMoatSite=c.ao.moatClientSlicer1;b.zMoatAT=c.ao.zMoatAT||"-";b.ab=c.an;b.ac=1;b.zMoatSeg=Number(3E4<=b.ah&&b.hasOwnProperty("ai"));b.it=a.n.k;c.bi=c.bg;
c.bm=c.bk;e=k(b,e);v.yh.yi(e+"&cs=0",V,Z)}};a.i.d=function(a,b){if(2!==a.an||1!==b.e&&3!==b.e){var d=fa;(new Image(1,1)).src=d}};a.i.e=function(a,b){return k(a,b)};a.i.f=function(c){var b={e:16};b.q=c.aq[16]++;a.i.a(c,b)}})(m);(function(a){function k(a,b,d,e){var g=(new q).getTime();this.tLast=this.tCur=0;this.update=function(b){var d=(new q).getTime();a(b)&&(b=r.min(d-g,1E3),this.tCur+=b,"number"===typeof e&&this.tCur>e&&(this.tCur=e));g=d};this.getQs=function(a){data=this.query(a);this.tLast=this.tCur;
return data};this.query=function(a){a=a||{};this.tLast>this.tCur&&(this.tLast=this.tCur);a[b]=this.tCur;a[d]=this.tLast;return a}}function h(){if(a.focus.pageIsVisible()&&"undefined"===typeof v.z){v.z=new q-U;a:{var c=void 0,b;for(b in t)if(t.hasOwnProperty(b)&&(c=t[b])&&"undefined"!==typeof c.ao){if(c.ce)break a;var d={e:4};d.q=c.aq[4]++;d.ai=v.z;a.i.a(c,d);c.ce=!0}a.c.c(x,"scroll",h,"onScroll")}}}a.e={};a.e.k=function(){a.c.b(x,"scroll",h,"onScroll");a.focus.setFocusListeners()};a.e.h=function(c,
b){try{var d=c.aa;b=b||c.WINDOW||a.e.a(d);return d&&b&&(d.parentNode||d.parentElement)?!0:!1}catch(e){return!1}};a.e.j=function(){var c,b;for(b in t)t.hasOwnProperty(b)&&(c=t[b],a.e.h(c,c.WINDOW)?c.counters.update(c):a.e.i(c))};a.e.i=function(c){!0!==c.em?a.i.c(c):(clearTimeout(c.cc),c.ep=!0,delete t[c.zr],a.h.a(c,"remove"),a.k.f(c.zr),c.aa=null)};a.e.e=function(c){c.eq||(c.eq=!0);var b={e:5};b.q=c.aq[5]++;a.i.a(c,b)};a.e.d=function(c){var b;c.elementRect?(b=c.elementRect.right-c.elementRect.left,
c=c.elementRect.bottom-c.elementRect.top):(b=c.aa.offsetWidth,c=c.aa.offsetHeight);return 3>b||3>c||a.focus.pageIsPrerendered()?!0:!1};a.e.l=function(a){var b=1;screen.deviceXDPI?b=screen.deviceXDPI/screen.systemXDPI:a.devicePixelRatio&&"undefined"!==typeof a.mozInnerScreenX&&(b=a.devicePixelRatio);return{w:b*screen.width,h:b*screen.height}};a.e.a=function(a){try{var b=a&&a.ownerDocument;return b&&(b.defaultView||b.parentWindow)}catch(d){return!1}};a.e.g=function(c){c.counters={};c.counters.laxDwell=
new k(function(){return!a.focus.pageIsPrerendered()},"bu","cd");c.counters.strictDwell=new k(a.focus.pageIsVisible,"ah","am");c.counters.query=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.query&&e.query(a)}return a};c.counters.getQs=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.getQs&&e.getQs(a)}return a};c.counters.update=function(a){for(var c in this)if(this.hasOwnProperty(c)){var e=this[c];
"function"===typeof e.update&&e.update(a)}}};a.e.b=function(c,b){for(var d=[],e,g=0;g<ga;g++)if(b!=b.parent){if(e=a.o.c(c,b))d.push(e);else break;b=b.parent;c=e}else break;return d};a.e.m=function(){for(var c in t)if(t.hasOwnProperty(c)){var b=t[c];if(b){var d={e:21};d.q=b.aq[21]++;a.i.a(b,d)}}};a.e.f=function(c){var b={e:9};b.q=c.aq[9]++;c.BEACON_LAST_SENT_AT=+new q;a.i.a(c,b)}})(m);(function(a){a.o={};a.o.b=function(k){try{if(k.moatHostileIframe)return null;if(k.src&&k.src.slice&&"http"===k.src.slice(0,
4)&&a.a.i(k.src)!=a.a.i(x.location.toString()))return k.moatHostileIframe=!0,null;var h=k&&(k.contentDocument||k.contentWindow&&k.contentWindow.document);if(h&&"string"===typeof h.location.toString())return h;k.moatHostileIframe=!0;return null}catch(c){return k.moatHostileIframe=!0,null}};a.o.c=function(k,h){h=h||a.e.a(k);try{return h&&h.frameElement}catch(c){return!1}};a.o.a=function(k){return(k=a.o.c(k))?k.parentNode:null}})(m);(function(a){a.q={};a.q.a=function(k){k[a.b.d]=k[a.b.d]||{zs:!1,zr:0,
h:0,m:0,i:{}};var h=k[a.b.d];"undefined"===typeof h.v&&(h.v=F?"undefined"===typeof k.document.hasFocus||D?!0:k.document.hasFocus():!0);h.ye||(h.ye=function(){this.v=!0});h.yd||(h.yd=function(){this.v=!1})}})(m);(function(a){var k=function(a,c){function b(a,b,c){a&&f.push({qs:a,jsd:b,fld:c});if(0===k&&0<f.length)if(k+=1,a=f.shift(),a.fld&&q&&m&&m.sendMessage)try{m.sendMessage(a)}catch(d){q=!1,e(a)}else e(a)}function d(){try{return new t(1,1)}catch(a){var b=window.document.createElement("img");b.height=
1;b.width=1;return b}}function e(a){var b=d();b.toSend=a;b.onerror=function(){var a=this.toSend;l+=1;var b=(a.jsd+"/pixel.gif?"+a.qs).length;2>l?e(a):v&&b>x&&g()};b.onload=function(){g()};b.src=a.jsd+"/pixel.gif?"+a.qs}function g(){0<k&&(k-=1,b())}var f=[],k=0,l=0,m=!1,q=!1,t,r=c[a];r.yh={};r=r.yh;t=c.Image;r.yi=function(a,c,d){b(a,c,d)};r.yk=function(b){m=!0;var c=a+".yh.",d={},e;try{e=window.location.protocol}catch(f){e=document.createElement("a"),e.href="",e=e.protocol}d.src="https:"===e?"https://z.moatads.com/swf/MessageSenderV2.swf":
"http://s.moatads.com/swf/MessageSenderV2.swf";d.flashVars="r="+c+"zb&s="+c+"zc&e="+c+"zd&td="+b;return d};r.yj=function(){return!1===m};r.zb=function(){try{if(!0===m){var a=c.document.getElementById("moatMessageSender");a&&!a.sendMessage&&(a=c.document.getElementById("moatMessageSenderEmbed"));a&&a.sendMessage&&(q=!0,m=a)}}catch(b){}};r.zc=function(){try{g()}catch(a){}};r.zd=function(a){try{q=!1,a&&a.jsd&&f.push(a),g()}catch(b){}};var s,v,x=2083;try{s=document.createElement("div"),s.innerHTML="\x3c!--[if IE 8]>x<![endif]--\x3e",
v="x"===s.innerHTML}catch(y){v=!1}}.toString();a.r={};a.r.a=function(h){if(!v.yh)if("undefined"!==typeof h.eval)h.eval("("+k+")('"+a.b.d+"',window)");else{var c=h.document.createElement("script");c.type="text/javascript";c.text="("+k+")('"+a.b.d+"',window)";h.document.body.insertBefore(c,h.document.body.childNodes[0])}}})(m);if(m.a.m())return!1;var L="NYTIMES2",ca="nyt952824751",Y="099702a-clean",U=m.b.i,da=m.b.k,y="moatFound"+L,T="__moat__"+L,fa="",ea=m.b.l,F=m.b.a,Z="afs.moatads.com",V,E=0,
O,S,J={},ga=50,M=[],N=[],t={},X={15:"",12:"",6:"",7:""};V="//v3.moatads.com";var x=m.b.c;m.q.a(x);var v=x[m.b.d];window[m.b.d]=v;m.r.a(x);m.a.i(F?x.location.href:x.document.referrer)||m.a.i(window.location.href);var C=m.a.r();if(!C)return!1;m.s=C;m.a.s(C);var D=m.a.j();(function(a){E=v.h;v.h++;v.i[E]=!1;!1===v.zs&&(m.e.k(),v.zs=!0);m.c.d(function(){m.e.j();for(var a in t)t.hasOwnProperty(a)&&m.k.c(t[a])},200);var k=!1;m.c.b(window,"unload",function(){k||(m.e.m(),k=!0)},!1);m.c.b(window,"beforeunload",
function(){k||(m.e.m(),k=!0)},!1);m.c.d(m.h.b,100);m.a.d()&&m.c.e(W,3E5);"undefined"===typeof a&&(a=m.p.b(C));var h=C.parentNode;m.c.e(function(){!1===v.i[E]&&(m.i.b(11,a),W())},1E4);m.i.b(17,a);m.n.a(h,a);v.alreadyRequestedContent||(v.alreadyRequestedContent=!0,ba(a))})()})(Date,Math)}catch(e$$50){var msg=e$$50.name+" in closure: "+e$$50.message+", stack="+e$$50.stack;try{var pxSrc="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("NYTIMES2")+"&ac=1&k="+escape(msg)+"&ar="+
escape("099702a-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,1);px.src=pxSrc}catch(e$$51){}};
